### PR TITLE
add songpage

### PR DESCRIPTION
**Pull request by ann0605**

### CODE REVIEW

**Review by Nlopierre — COMMENTED** [review]
Do you have an example of a song Id to test the URL?

**Comment by ann0605** [comment]
test with song/1

**Comment by kaleapalmer** [comment]
The song page looks really good. Do we want to show the royalty list to users that are not logged in?

**Comment by ann0605** [comment]
there is no security check at the moment, I think we should only show it to people who are logged in and redirect to log in page if not.

**Comment by kaleapalmer** [comment]
Do you want to add that before this merge is approved?

**Review by kaleapalmer — APPROVED** [review]
The song page looks bomb and I approve. Maybe add a security check if the user is logged in.

**Pull request merged**
